name: Build libspecprober library (FreeBSD - AMD64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Test
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.0"
          arch: "x86_64"
          run: |
            pkg install -y cmake ninja
            cd interop/libspecprober ; cmake . ; make
            cd ../libspecprober_ldelf_fbsd ; cmake . ; make
      - name: libspecprober artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "libspecprober library FreeBSD AMD64"
          path: interop/libspecprober/libspecprober.so
          archive: false
      - name: libspecprober_ldelf_fbsd artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "libspecprober_ldelf_fbsd library FreeBSD AMD64"
          path: interop/libspecprober_ldelf_fbsd/libspecprober_ldelf_fbsd.so
          archive: false
